FAIL
Kernel panic in run: PANIC at ../../lib/kernel/list.c:78 in list_next(): assertion `is_head (elem) || is_interior (elem)' failed.
Call stack: 0x80042138dc 0x8004213b58 0x800421462d 0x8004214a4f 0x800420a93a 0x800420a287 0x8004216a0f 0x8004216abc 0x8004210ddf 0x8004216dd7 0x8004219b3e 0x8004216d18 0x8004206636 0x8004206783 0x8004206120
Translation of call stack:
0x00000080042138dc: debug_panic (lib/kernel/debug.c:32)
0x0000008004213b58: list_next (lib/kernel/list.c:79)
0x000000800421462d: find_end_of_run (lib/kernel/list.c:347 (discriminator 2))
0x0000008004214a4f: list_sort (lib/kernel/list.c:404 (discriminator 2))
0x000000800420a93a: return_priority (threads/synch.c:430)
0x000000800420a287: lock_release (threads/synch.c:253)
0x0000008004216a0f: release_console (lib/kernel/console.c:103)
0x0000008004216abc: vprintf (lib/kernel/console.c:125)
0x0000008004210ddf: printf (lib/stdio.c:80)
0x0000008004216dd7: msg (tests/threads/tests.c:72)
0x0000008004219b3e: test_priority_donate_chain (tests/threads/priority-donate-chain.c:76 (discriminator 4))
0x0000008004216d18: run_test (tests/threads/tests.c:57)
0x0000008004206636: run_task (threads/init.c:252)
0x0000008004206783: run_actions (threads/init.c:297)
0x0000008004206120: main (threads/init.c:125)
